"""
AI investigation report generator (FIGAE / Module 2, §7).

Turns a fraud cluster into an investigation-ready package — the structured
summary the PDF exemplar (FC-021) shows, plus a plain-language narrative and a
suggested-action list keyed off what the cluster actually contains.

The generator is deterministic and offline by default: the numbers are the
cluster's own, the narrative is templated from them, and the actions are chosen
by simple rules over the evidence (shared UPIs ⇒ "freeze these VPAs"). An LLM, if
one is configured, may *rephrase* the narrative into fluent investigator prose —
but exactly like `services/api/llm.py`, it is handed only the decided facts and
may never invent a case, a number, or a risk level. The intelligence package has
to be defensible as evidence; a hallucinated linked account is the opposite of
that.
"""

from __future__ import annotations

import time
from typing import Any, Dict, Optional

from .graph import ClusterSummary
from .repository import scam_name
from .scoring import factor_breakdown


def _suggested_actions(cluster: ClusterSummary) -> list[str]:
    """Rule-based next steps, tuned to the cluster's evidence. Not generic
    advice — an action list that says the same thing for every cluster is one an
    investigator ignores."""
    actions: list[str] = []
    if cluster.shared_upi_ids:
        actions.append(
            f"Freeze the {len(cluster.shared_upi_ids)} shared UPI ID(s) "
            f"({', '.join(cluster.shared_upi_ids[:3])}) with the sponsor banks."
        )
    if cluster.shared_wallets:
        actions.append(
            f"Flag the shared wallet address(es) with the exchange and FIU-IND."
        )
    if cluster.shared_phones:
        actions.append(
            f"Request CDRs and issue a monitoring order on the "
            f"{len(cluster.shared_phones)} reused number(s)."
        )
    if len(cluster.states) >= 2:
        actions.append(
            f"Open inter-state coordination across {', '.join(cluster.states)} — "
            "this crew is operating across jurisdictions."
        )
    if cluster.risk in ("HIGH", "CRITICAL"):
        actions.append(
            "Escalate to I4C / MHA as an active campaign and pre-position a "
            "victim-alert list for the reused numbers."
        )
    actions.append("Track the cluster for new cases as Module 1 keeps detecting.")
    return actions


def investigation_report(cluster: ClusterSummary) -> Dict[str, Any]:
    """The structured investigation package for one cluster. Mirrors the PDF's
    FC-021 exemplar field-for-field, then adds provenance and a narrative."""
    breakdown = factor_breakdown(
        n_cases=cluster.size,
        total_loss=cluster.total_loss_inr,
        shared_infra=len(cluster.shared_phones) + len(cluster.shared_upi_ids)
        + len(cluster.shared_wallets),
        n_states=len(cluster.states),
        peak_threat=cluster.peak_threat,
        mean_threat=cluster.mean_threat,
    )

    narrative = _narrative(cluster)

    return {
        "cluster_id": cluster.cluster_id,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "generator": "AegisAI / FIGAE — Fraud Intelligence & Geospatial Analytics Engine",
        "summary": {
            "linked_cases": cluster.size,
            "primary_scam": scam_name(cluster.primary_scam),
            "shared_phone_numbers": len(cluster.shared_phones),
            "shared_upi_ids": len(cluster.shared_upi_ids),
            "shared_wallets": len(cluster.shared_wallets),
            "affected_states": cluster.states,
            "total_loss_inr": round(cluster.total_loss_inr, 2),
            "risk_level": cluster.risk,
            "risk_score": round(cluster.risk_score, 1),
            "is_campaign": cluster.is_campaign,
        },
        "evidence": {
            "shared_phones": cluster.shared_phones,
            "shared_upi_ids": cluster.shared_upi_ids,
            "shared_wallets": cluster.shared_wallets,
            "case_ids": cluster.case_ids,
        },
        "risk_factors": breakdown,
        "narrative": narrative,
        "suggested_actions": _suggested_actions(cluster),
        "disclaimer": (
            "Generated by AegisAI FIGAE from correlated fraud reports. Links are "
            "derived from shared infrastructure and are investigative leads, not "
            "determinations of guilt. Verify before any enforcement action."
        ),
    }


def _narrative(cluster: ClusterSummary) -> str:
    """A few sentences an investigator can drop into a case file. Templated from
    the cluster's own figures — no invented facts."""
    parts = [
        f"Cluster {cluster.cluster_id} links {cluster.size} fraud cases into a "
        f"single {scam_name(cluster.primary_scam).lower()} operation."
    ]
    infra = []
    if cluster.shared_phones:
        infra.append(f"{len(cluster.shared_phones)} reused phone number(s)")
    if cluster.shared_upi_ids:
        infra.append(f"{len(cluster.shared_upi_ids)} shared UPI ID(s)")
    if cluster.shared_wallets:
        infra.append(f"{len(cluster.shared_wallets)} common wallet(s)")
    if infra:
        parts.append(
            "The cases are connected by " + ", ".join(infra)
            + " — the signature of a coordinated crew rather than unrelated incidents."
        )
    if cluster.states:
        parts.append(
            f"It spans {', '.join(cluster.states)}, with a combined reported "
            f"exposure of ₹{cluster.total_loss_inr:,.0f}."
        )
    parts.append(
        f"Module 1 scored the linked calls at a peak threat of "
        f"{cluster.peak_threat:.0f}/100; the cluster's dynamic risk is "
        f"{cluster.risk} ({cluster.risk_score:.0f}/100)."
    )
    return " ".join(parts)


def enhance_narrative(report: Dict[str, Any]) -> Optional[str]:
    """Optionally rephrase the narrative via the configured LLM. Facts-in,
    prose-out; returns None if no backend is available, and the caller keeps the
    templated narrative. Never changes a number."""
    from .. import llm

    if not llm.available():
        return None
    brief = {
        "summary": report["summary"],
        "evidence": {
            "shared_phones": report["evidence"]["shared_phones"],
            "shared_upi_ids": report["evidence"]["shared_upi_ids"],
        },
        "risk_factors": [f["factor"] for f in report["risk_factors"][:3]],
    }
    import json

    prompt = (
        "Rewrite this fraud-cluster summary as two or three sentences of clear "
        "investigator prose. Do not change or add any number, name, or risk "
        "level.\n\n" + json.dumps(brief, ensure_ascii=False, indent=2)
    )
    try:
        # Reuse the same guarded backend the analyzer uses; it enforces the
        # no-new-facts system prompt.
        return llm._BACKENDS[llm.settings.llm_backend](prompt)  # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001 — prose is a nice-to-have, never a 500
        return None
