"""
Evidence package — the escalation artifact (Module 1, §11 Alert Engine).

When a call crosses into danger, an in-app meter is not enough: the value to a
telecom provider or a cybercrime cell is a *structured, auditable package* they
can act on and, ideally, submit. The hackathon's evaluation says it outright —
"auditability of intelligence packages for legal admissibility". So this module
turns a live `Session` into a single, self-describing document:

  * the verdict and the *named signals* that produced it (never a bare score),
  * the identity fraud evidence (Trust Passport) and the caller-ID spoofing
    evidence (Number Intelligence), each check with its citation,
  * the manipulation-stage timeline, so a reader can see the arc, not a snapshot,
  * the full transcript as the underlying evidence,
  * and explicit reporting guidance (1930 / cybercrime.gov.in / I4C).

It is assembled here, once, as a plain JSON-serialisable dict. The JSON endpoint
returns it verbatim and the PDF renderer draws from the same dict — two views of
one source, the same discipline the whole product runs on. Nothing here is
generated or embellished: every field is copied from state the engine already
computed and can defend.
"""

from __future__ import annotations

import time
import uuid
from typing import TYPE_CHECKING, Any, Dict

if TYPE_CHECKING:  # avoid a circular import at runtime
    from .session import Session

REPORT_SCHEMA_VERSION = 1

#: How the incident is classified for an MHA / I4C reader. Keyed off the peak
#: stage, so a call that never got past a scare reads differently from one that
#: reached a payment attempt.
_INCIDENT_BY_STAGE = {
    "AUTHORITY_CLAIM": "Impersonation of a law-enforcement / government authority",
    "FEAR_INDUCTION": "Coercion by false criminal allegation ('digital arrest')",
    "ISOLATION": "Coercive isolation ('digital arrest') in progress",
    "VERIFICATION_DEMAND": "Attempted credential / KYC harvesting",
    "PAYMENT_SETUP": "Attempted fraudulent fund transfer (setup)",
    "PAYMENT_EXECUTION": "Attempted fraudulent fund transfer (execution)",
}

_REPORTING_GUIDANCE = [
    "Call the national cyber-fraud helpline 1930 immediately if money has moved.",
    "File a complaint at cybercrime.gov.in (I4C / NCRB) and attach this package.",
    "Do not delete the call log, messages, or any payment screenshots — they are evidence.",
    "Your bank's fraud line can attempt a transaction reversal within the golden hour.",
]

DISCLAIMER = (
    "Generated by AegisAI — an assistive scam-detection system. This "
    "package summarises automated signals and is intended to support, not "
    "replace, human review and official reporting. It is not a legal "
    "determination of guilt."
)


def _stage_timeline(session: "Session") -> list[Dict[str, Any]]:
    """First appearance of each caller stage, in order — the manipulation arc."""
    timeline: list[Dict[str, Any]] = []
    seen: set[str] = set()
    for u in session.utterances:
        if u.speaker != "CALLER" or u.stage in seen or u.stage == "BENIGN":
            continue
        seen.add(u.stage)
        timeline.append({
            "stage": u.stage,
            "at_s": round(u.t1, 1),
            "first_utterance": u.text,
        })
    return timeline


def _citations(session: "Session", number_intel: Dict[str, Any]) -> list[str]:
    seen: list[str] = []

    def add(src: str | None) -> None:
        if src and src not in seen:
            seen.append(src)

    for check in session.passport.snapshot().checks:
        if check.verdict == "FAIL":
            add(check.source)
    for check in number_intel.get("checks", []):
        if check.get("verdict") == "FAIL":
            add(check.get("source"))
    return seen


def build_evidence_package(session: "Session") -> Dict[str, Any]:
    """Assemble the full, JSON-serialisable evidence package for a session."""

    frame = session.frame()  # single source for the live-state fields
    passport = frame.get("trust_passport") or {}
    number_intel = frame.get("number_intel") or {}
    threat = frame.get("threat") or {}

    incident_type = _INCIDENT_BY_STAGE.get(
        session.peak_stage, "Suspected fraudulent call"
    )

    # Failed checks, flattened into a single "evidence" list a reader can scan —
    # each an independently-citable fact rather than a paragraph.
    evidence: list[Dict[str, Any]] = []
    for check in passport.get("checks", []):
        if check.get("verdict") == "FAIL":
            evidence.append({
                "category": "Identity",
                "finding": check.get("name"),
                "detail": check.get("detail"),
                "source": check.get("source"),
            })
    for check in number_intel.get("checks", []):
        if check.get("verdict") == "FAIL":
            evidence.append({
                "category": "Caller number",
                "finding": check.get("name"),
                "detail": check.get("detail"),
                "source": check.get("source"),
            })

    return {
        "report_id": f"KVCH-{uuid.uuid4().hex[:12].upper()}",
        "schema_version": REPORT_SCHEMA_VERSION,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "generator": "AegisAI — Real-Time Scam Session Intelligence Engine",
        "disclaimer": DISCLAIMER,

        "incident": {
            "type": incident_type,
            "peak_threat": round(session.peak_threat, 1),
            "peak_stage": session.peak_stage,
            "final_threat": threat.get("score", 0.0),
            "final_level": threat.get("level", "CALM"),
        },

        "call": {
            "session_id": session.id,
            "caller_number": session.caller_number,
            "duration_s": round(session.t, 1),
            "status": session.status,
            "utterance_count": len(session.utterances),
        },

        "assessment": {
            "claimed_identity": passport.get("claimed_identity"),
            "identity_trust_pct": passport.get("final_trust_pct"),
            "caller_number_risk": number_intel.get("risk"),
            "caller_number_verdict": number_intel.get("verdict"),
            "drivers": threat.get("drivers", []),
        },

        "evidence": evidence,
        "stage_timeline": _stage_timeline(session),

        "intervention": {
            "guardian_state": frame.get("guardian", {}).get("state"),
            "guardian_name": frame.get("guardian", {}).get("name"),
            "payment_state": frame.get("payment", {}).get("state"),
            "payment_amount_inr": frame.get("payment", {}).get("amount_inr"),
            "payment_held_reason": frame.get("payment", {}).get("held_reason"),
        },

        "transcript": [
            {
                "t_s": round(u.t1, 1),
                "speaker": u.speaker,
                "stage": u.stage if u.speaker == "CALLER" else None,
                "text": u.text,
            }
            for u in session.utterances
        ],

        "citations": _citations(session, number_intel),
        "reporting_guidance": _REPORTING_GUIDANCE,
        "degraded": frame.get("degraded", []),
    }
