"""
Structured complaint generation (CFSRP / Module 3, Step 6).

Turns a preserved citizen verification into the cybercrime-complaint package the
PDF specifies: incident summary, scam type, timeline, extracted entities,
supporting evidence, and the AI threat analysis — everything an I4C /
cybercrime.gov.in filing needs, assembled so the citizen is not left staring at
a blank form during the worst hour of their week.

It reuses the same PDF renderer as the Module 1 evidence package
(`engine/report_pdf.py`), mapped into that renderer's shape, so a citizen
complaint and an investigator evidence package are the same kind of document —
one renderer, one look, one standard of auditability.
"""

from __future__ import annotations

import time
import uuid
from typing import Any, Dict, List

from ..intel.entities import extract_from_text

_GUIDANCE = [
    "Call 1930 immediately if any money has been transferred.",
    "File this complaint at cybercrime.gov.in (I4C) and keep the acknowledgement number.",
    "Do not delete any messages, call recordings, or payment screenshots — they are evidence.",
    "Ask your bank's fraud line to attempt a reversal within the golden hour.",
]


def build_complaint(result: Dict[str, Any], *, submitted_text: str = "",
                    channel: str = "web", city: str | None = None) -> Dict[str, Any]:
    """Assemble the structured complaint package from a verification result."""
    analysis = result.get("analysis", {}) or {}
    intel = result.get("intel", {}) or {}
    ent = extract_from_text(submitted_text or "")

    entities = {
        "phones": list(ent.phones),
        "upi_ids": list(ent.upi_ids),
        "emails": list(ent.emails),
        "wallets": list(ent.wallets),
        "amounts": list(ent.amounts),
    }
    # Fold in the caller number the verification carried, and the analyzer's own
    # extracted UPI, if present and not already listed.
    number_intel = analysis.get("number_intel") or {}
    if number_intel.get("number"):
        digits = "".join(ch for ch in str(number_intel["number"]) if ch.isdigit())[-10:]
        if digits and digits not in entities["phones"]:
            entities["phones"].append(digits)
    upi_payload = analysis.get("upi") or {}
    if upi_payload.get("vpa") and upi_payload["vpa"] not in entities["upi_ids"]:
        entities["upi_ids"].append(upi_payload["vpa"])

    return {
        "complaint_id": f"KVCH-CIT-{uuid.uuid4().hex[:10].upper()}",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "generator": "KAVACH / CFSRP — Citizen Fraud Shield & Response Platform",
        "channel": channel,
        "incident": {
            "summary": result.get("summary")
            or "Suspected fraud reported by a citizen through KAVACH.",
            "scam_type": _scam_label(result.get("stage")),
            "stage": result.get("stage"),
            "verdict": result.get("verdict"),
            "threat_level": result.get("level"),
            "score": result.get("score"),
            "city": city,
        },
        "entities": entities,
        "linked_intelligence": {
            "known_infrastructure": intel.get("known_infrastructure", False),
            "clusters": intel.get("clusters", []),
            "matched_entities": intel.get("matched_entities", []),
        },
        "ai_analysis": {
            "drivers": analysis.get("drivers", []),
            "findings": analysis.get("findings", []),
            "citations": analysis.get("citations", []),
        },
        "supporting_evidence": {
            "submitted_text": submitted_text[:4000],
            "transcript_lines": [
                {"speaker": l.get("speaker"), "text": l.get("text"), "stage": l.get("stage")}
                for l in analysis.get("lines", [])
            ][:100],
        },
        "reporting_guidance": _GUIDANCE,
        "disclaimer": (
            "Generated by KAVACH to assist a citizen in reporting a suspected "
            "fraud. It summarises automated analysis and is intended to support, "
            "not replace, an official complaint at 1930 / cybercrime.gov.in."
        ),
    }


_SCAM_BY_STAGE = {
    "AUTHORITY_CLAIM": "Impersonation of authority",
    "FEAR_INDUCTION": "Digital arrest / coercion by false allegation",
    "ISOLATION": "Digital arrest (coercive isolation)",
    "VERIFICATION_DEMAND": "Credential / KYC harvesting",
    "PAYMENT_SETUP": "Fraudulent fund-transfer setup",
    "PAYMENT_EXECUTION": "Fraudulent fund transfer",
}


def _scam_label(stage: str | None) -> str:
    return _SCAM_BY_STAGE.get(stage or "", "Suspected fraudulent contact")


def complaint_to_evidence_package(complaint: Dict[str, Any]) -> Dict[str, Any]:
    """Map a citizen complaint into the shape `engine/report_pdf.render_pdf`
    expects, so the same renderer produces the citizen's PDF. One document
    standard across both modules."""
    incident = complaint.get("incident", {})
    entities = complaint.get("entities", {})
    evidence: List[Dict[str, Any]] = []
    for f in complaint.get("ai_analysis", {}).get("findings", []):
        evidence.append({
            "category": "Signal",
            "finding": f.get("label"),
            "detail": f.get("detail"),
            "source": f.get("source"),
        })
    for cluster in complaint.get("linked_intelligence", {}).get("clusters", []):
        evidence.append({
            "category": "Fraud network",
            "finding": f"Linked to cluster {cluster.get('cluster_id')}",
            "detail": f"{cluster.get('primary_scam')} — {cluster.get('size')} cases, "
                      f"risk {cluster.get('risk')}",
            "source": None,
        })

    transcript = [
        {"t_s": None, "speaker": l.get("speaker"), "stage": l.get("stage"), "text": l.get("text")}
        for l in complaint.get("supporting_evidence", {}).get("transcript_lines", [])
    ]

    return {
        "report_id": complaint.get("complaint_id"),
        "generated_at": complaint.get("generated_at"),
        "disclaimer": complaint.get("disclaimer"),
        "incident": {
            "type": incident.get("scam_type"),
            "peak_threat": incident.get("score"),
            "peak_stage": incident.get("stage"),
            "final_threat": incident.get("score"),
            "final_level": incident.get("threat_level"),
        },
        "call": {
            "session_id": complaint.get("complaint_id"),
            "caller_number": (entities.get("phones") or [None])[0],
            "duration_s": None,
        },
        "assessment": {
            "claimed_identity": None,
            "identity_trust_pct": None,
            "caller_number_risk": None,
            "caller_number_verdict": None,
            "drivers": complaint.get("ai_analysis", {}).get("drivers", []),
        },
        "evidence": evidence,
        "stage_timeline": [],
        "transcript": transcript,
        "citations": complaint.get("ai_analysis", {}).get("citations", []),
        "reporting_guidance": complaint.get("reporting_guidance", []),
        "degraded": [],
    }
